LOGIN = '/login/'
REGISTER = '/register/'
LOGOUT = '/logout/'
SEND_CHAT_MESSAGE = '/send_chat_message/'
SEND_GROUP_MESSAGE = '/send_group_message/'
SHOW_CHATS = '/show_chats/'
VIEW_CHAT = '/view_chat/'
VIEW_ONLINE_USERS = '/view_online_users/'