version: '1'

services:
  redis:
    image: redis
    container_name: chat-server-redis
    hostname: redis
    restart: always
    ports:
      - "26000:6379"
    networks:
      - internal_network

  server:
    build:
      context: .
    ports:
      - "80:8000"
    networks:
      - internal_network

networks:
  internal_network:
